### ISSUE TITLE
Using progress=True results in hung process

### ISSUE THREAD

**Issue by tlogan2000** [bird-house/finch#45] opened 2019-10-25 12:49 UTC
## Description
Running a finch subset gridpoint using progress=True never gets beyond 'process accepted'
Running directly on small data sets works fine but a large (e.g. NcML aggregate) results in a server timeout (I think)

Describe what you were trying to get done or your feature request.

## Environment
https://pavics.ouranos.ca/twitcher/ows/proxy/finch/wps

## Steps to Reproduce

```
from birdy import WPSClient
import xarray as xr
import numpy as np
import os
url = 'https://pavics.ouranos.ca/twitcher/ows/proxy/finch/wps'
wps_sync = WPSClient(url)
wps_prog = WPSClient(url, progress=True)

# single year file 
tasmin = "https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/nrcan/nrcan_canada_daily/tasmin/nrcan_canada_daily_tasmin_2010.nc"

#ncml aggregate (all years - 3 variables)
ncml = 'https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/ouranos/cb-oura-1.0/MPI-ESM-LR/rcp85/day/MPI-ESM-LR_rcp85_allvars.ncml'

# non progress small file == OK
resp = wps_sync.subset_gridpoint(resource=tasmin, lat=47.0, lon=-78.0)

# non progress large file == ERROR
resp = wps_sync.subset_gridpoint(resource=ncml, lat=47.0, lon=-78.0)

# progress=True small file == Stops at 'ProcessAccepted'  - 10% complete
resp = wps_prog.subset_gridpoint(resource=tasmin, lat=47.0, lon=-78.0)

# progress=True large file == Stops at 'ProcessAccepted'  - 10% complete
resp = wps_prog.subset_gridpoint(resource=ncml, lat=47.0, lon=-78.0)

```

## Additional Information
Re-running mutliple calls to wps_prog will eventually fill up the queue and gives a 'too many parrallel process error' 

I think this is  a general problem and not limited to subsetting functions.  I am unsure if this is a code/finch issue or a configuration issue on the server

Links to other issues or sources.

**Comment by davidcaron** [comment] 2019-10-25 12:52
My first guess is that this is related to https://github.com/Ouranosinc/PAVICS/pull/173

**Comment by tlvu** [comment] 2019-10-25 12:58
Medus should have autodeployed DavidC fix by now.  Can try on Medus to confirm DavidC guess.
________________________________

**Comment by davidcaron** [comment] 2019-10-25 13:01
> 
> Medus should have autodeployed DavidC fix by now. Can try on Medus to confirm DavidC guess.

It will not 100% confirm it if it works, because the queue in Medus may not have been in the same state as the one on pavics.ouranos.ca

**Comment by tlogan2000** [comment] 2019-10-25 13:08
I will give it a try on medus

**Comment by tlogan2000** [comment] 2019-10-25 13:20
@tlvu isn't this your day off?  go back to sleep!!!

**Comment by davidcaron** [comment] 2019-11-05 18:38
I just talked with Travis, it doesn't seem to be related to the queue according to the logs. The task starts to process, but just hangs there when the process is async... I'll take a look more closely at this, I'm not sure why at first glance.

**Comment by tlogan2000** [comment] 2019-11-06 20:28
@Zeitsperre can you follow up on this tomorrow at CRIM please?

**Comment by tlvu** [comment] 2019-12-02 20:50
Discovered and manually cleared hung process on Boreas today (broken Jenkins run for a few days).  Note it's the `frost_days` process and the `percent_done` is `5%` instead of hanging at the usual `10%`:
```
$ birdhouse/scripts/clear-running-wps-jobs-in-db.sh finch
+ docker exec postgres psql -U pavics finch -c 'select * from pywps_requests where percent_done > -1 and percent_done < 100.0;'
                 uuid                 | pid | operation | version |         time_start         |          time_end          | identifier |      message       | percent_done | status 
--------------------------------------+-----+-----------+---------+----------------------------+----------------------------+------------+--------------------+--------------+--------
 57d8444c-1309-11ea-9f74-0242ac120003 |  60 | execute   | 1.0.0   | 2019-11-30 00:35:43.76633  | 2019-11-30 00:35:43.928857 | frost_days | Processing started |            5 |      2
 6f2ae88e-1309-11ea-8028-0242ac120003 | 223 | execute   | 1.0.0   | 2019-11-30 00:36:22.895755 | 2019-11-30 00:36:23.048464 | frost_days | Processing started |            5 |      2
(2 rows)

+ set +x

WARNING: this will crash all the above requests if currently still processing

Clear those jobs? (Ctrl-C to cancel, any keys to continue)

+ docker exec postgres psql -U pavics finch -c 'delete from pywps_requests where percent_done > -1 and percent_done < 100.0;'
DELETE 2
```

Does the WPS logging log the IP that queued the process?  If it has the user, it would even be better.

**Comment by tlvu** [comment] 2019-12-09 11:21
`frost_days` stuck at `5% percent_done` again on prod Boreas, breaking Jenkins nightlies:
```
$ ./birdhouse/scripts/clear-running-wps-jobs-in-db.sh finch
+ docker exec postgres psql -U pavics finch -c 'select * from pywps_requests where percent_done > -1 and percent_done < 100.0;'
                 uuid                 | pid | operation | version |         time_start         |          time_end          | identifier |      message       | percent_done | status 
--------------------------------------+-----+-----------+---------+----------------------------+----------------------------+------------+--------------------+--------------+--------
 806082d2-1889-11ea-ad81-0242ac120017 | 539 | execute   | 1.0.0   | 2019-12-07 00:35:43.163393 | 2019-12-07 00:35:43.320612 | frost_days | Processing started |            5 |      2
 a2417122-1889-11ea-b221-0242ac120017 | 648 | execute   | 1.0.0   | 2019-12-07 00:36:40.001827 | 2019-12-07 00:36:40.187065 | frost_days | Processing started |            5 |      2
(2 rows)

+ set +x

WARNING: this will crash all the above requests if currently still processing

Clear those jobs? (Ctrl-C to cancel, any keys to continue)

+ docker exec postgres psql -U pavics finch -c 'delete from pywps_requests where percent_done > -1 and percent_done < 100.0;'
DELETE 2
```
This is getting really annoying for Jenkins.

**Comment by davidcaron** [comment] 2019-12-09 16:35
@tlvu I'm starting to think that this is related to #55. When I send lots of requests to my local pavics instance for the frost_days process, I get the same traceback I got in the travis-ci logs... I will re-build finch with the newly merged fix, and try to reproduce.

**Comment by tlvu** [comment] 2019-12-09 16:41
> I'm starting to think that this is related to #55.

The finch in our prod server do not contain that PR yet.  Unless that PR fixed it.

**Comment by davidcaron** [comment] 2019-12-09 16:50
Yes, no problems with the new build. I'll make a new release and submit a PR to the pavics repo.

So this issue is fixed by #55.

**Closed** 2019-12-09 18:13 UTC

**Comment by tlvu** [comment] 2019-12-09 19:18
Another `frost_days` stuck just 8 hours after I have previously perform manual clean up on prod Boreas:
```
$ scripts/clear-running-wps-jobs-in-db.sh finch
+ docker exec postgres psql -U pavics finch -c 'select * from pywps_requests where percent_done > -1 and percent_done < 100.0;'
                 uuid                 | pid  | operation | version |         time_start         |          time_end          | identifier |           message           | percent_done | status 
--------------------------------------+------+-----------+---------+----------------------------+----------------------------+------------+-----------------------------+--------------+--------
 cdb28654-1a99-11ea-921a-0242ac120017 | 1297 | execute   | 1.0.0   | 2019-12-09 15:37:27.158398 | 2019-12-09 15:37:28.657933 | frost_days | Computing the output netcdf |           10 |      2
 b9a21b42-1aa4-11ea-8d89-0242ac120017 | 1513 | execute   | 1.0.0   | 2019-12-09 16:55:37.96067  | 2019-12-09 16:55:39.455133 | frost_days | Computing the output netcdf |           10 |      2
(2 rows)

+ set +x

WARNING: this will crash all the above requests if currently still processing

Clear those jobs? (Ctrl-C to cancel, any keys to continue)

+ docker exec postgres psql -U pavics finch -c 'delete from pywps_requests where percent_done > -1 and percent_done < 100.0;'
DELETE 2
```

**Comment by davidcaron** [comment] 2019-12-09 19:21
Wait for the deployment of 0.2.7, it should fix it. You will probably have to do one more manual clean after the deployment.

**Comment by tlvu** [comment] 2019-12-11 15:32
Another `frost_days` on prod Boreas:

```
$ ./birdhouse/scripts/clear-running-wps-jobs-in-db.sh finch
+ docker exec postgres psql -U pavics finch -c 'select * from pywps_requests where percent_done > -1 and percent_done < 100.0;'
                 uuid                 | pid  | operation | version |         time_start         |          time_end          | identifier |      message       | percent_done | status 
--------------------------------------+------+-----------+---------+----------------------------+----------------------------+------------+--------------------+--------------+--------
 4dacd796-1bae-11ea-80df-0242ac120017 | 2577 | execute   | 1.0.0   | 2019-12-11 00:36:42.967214 | 2019-12-11 00:36:43.140269 | frost_days | Processing started |            5 |      2
(1 row)

+ set +x

WARNING: this will crash all the above requests if currently still processing

Clear those jobs? (Ctrl-C to cancel, any keys to continue)

+ docker exec postgres psql -U pavics finch -c 'delete from pywps_requests where percent_done > -1 and percent_done < 100.0;'
DELETE 1
```

Really hope the new finch 0.2.7 can fix this but this deployment is blocked by the broken Magpie.  I'll revert the Magpie.

**Comment by tlvu** [comment] 2020-03-09 02:36
Another `frost_days` on prod Boreas breaking Jenkins with `Maximum number of parallel running processes reached. Please try later.`:

```
$ ./scripts/clear-running-wps-jobs-in-db.sh finch
+ docker exec postgres psql -U pavics finch -c 'select * from pywps_requests where percent_done > -1 and percent_done < 100.0;'
                 uuid                 | pid | operation | version |         time_start         |          time_end          | identifier |      message       | percent_done | status 
--------------------------------------+-----+-----------+---------+----------------------------+----------------------------+------------+--------------------+--------------+--------
 ea29805a-5ce6-11ea-94ad-0242ac12000c |   9 | execute   | 1.0.0   | 2020-03-03 00:35:44.393443 | 2020-03-03 00:35:46.766954 | frost_days | Processing started |            5 |      2
 15d745ac-5ce7-11ea-beb6-0242ac12000c | 126 | execute   | 1.0.0   | 2020-03-03 00:36:56.187097 | 2020-03-03 00:36:56.395356 | frost_days | Processing started |            5 |      2
(2 rows)

+ set +x

WARNING: this will crash all the above requests if currently still processing

Clear those jobs? (Ctrl-C to cancel, any keys to continue)

+ docker exec postgres psql -U pavics finch -c 'delete from pywps_requests where percent_done > -1 and percent_done < 100.0;'
DELETE 2
```

**Comment by davidcaron** [comment] 2020-03-09 13:52
If the crashed processes come from a jenkins run, could you try to find the jenkins logs that launched these 2 jobs? A traceback would really be helpful.

**Comment by tlvu** [comment] 2020-03-10 21:17
Again, sorry not had time to search old Jenkins logs, but logging here for occurrence count.
```
$ ./scripts/clear-running-wps-jobs-in-db.sh finch
+ docker exec postgres psql -U pavics finch -c 'select * from pywps_requests where percent_done > -1 and percent_done < 100.0;'
                 uuid                 | pid | operation | version |         time_start         |          time_end          | identifier |               message                | percent_done | status 
--------------------------------------+-----+-----------+---------+----------------------------+----------------------------+------------+--------------------------------------+--------------+--------
 6d02e866-6234-11ea-8a0f-0242ac120003 | 105 | execute   | 1.0.0   | 2020-03-09 18:33:09.496807 | 2020-03-09 18:33:40.291404 | frost_days | [####           ] | 32% Done |  7.2s |           32 |      2
 13c92baa-62f4-11ea-b881-0242ac120003 |   9 | execute   | 1.0.0   | 2020-03-10 17:25:03.323069 | 2020-03-10 17:25:06.264769 | frost_days | Processing started                   |            5 |      2
(2 rows)

+ set +x

WARNING: this will crash all the above requests if currently still processing

Clear those jobs? (Ctrl-C to cancel, any keys to continue)

+ docker exec postgres psql -U pavics finch -c 'delete from pywps_requests where percent_done > -1 and percent_done < 100.0;'
DELETE 2
```

**Comment by tlvu** [comment] 2020-03-13 00:27
```
$ ./scripts/clear-running-wps-jobs-in-db.sh finch
+ docker exec postgres psql -U pavics finch -c 'select * from pywps_requests where percent_done > -1 and percent_done < 100.0;'
                 uuid                 | pid | operation | version |         time_start         |          time_end          | identifier |               message                | percent_done | status 
--------------------------------------+-----+-----------+---------+----------------------------+----------------------------+------------+--------------------------------------+--------------+--------
 f1fe8652-64a4-11ea-8801-0242ac120003 |  58 | execute   | 1.0.0   | 2020-03-12 21:03:38.807785 | 2020-03-12 21:03:41.617734 | frost_days | Processing started                   |            5 |      2
 1d6ab112-64a5-11ea-8f86-0242ac120003 | 255 | execute   | 1.0.0   | 2020-03-12 21:04:51.416295 | 2020-03-12 21:05:22.221866 | frost_days | [####           ] | 32% Done |  7.1s |           32 |      2
(2 rows)

+ set +x

WARNING: this will crash all the above requests if currently still processing

Clear those jobs? (Ctrl-C to cancel, any keys to continue)

+ docker exec postgres psql -U pavics finch -c 'delete from pywps_requests where percent_done > -1 and percent_done < 100.0;'
DELETE 2
```

**Comment by tlvu** [comment] 2020-03-16 15:48
```
$ ./scripts/clear-running-wps-jobs-in-db.sh finch
+ docker exec postgres psql -U pavics finch -c 'select * from pywps_requests where percent_done > -1 and percent_done < 100.0;'
                 uuid                 | pid | operation | version |         time_start         |          time_end          | identifier |      message       | percent_done | status 
--------------------------------------+-----+-----------+---------+----------------------------+----------------------------+------------+--------------------+--------------+--------
 c0af91c6-658b-11ea-b60c-0242ac120003 | 357 | execute   | 1.0.0   | 2020-03-14 00:35:49.602284 | 2020-03-14 00:35:51.14363  | frost_days | Processing started |            5 |      2
 308f3e10-658c-11ea-a77c-0242ac120003 | 510 | execute   | 1.0.0   | 2020-03-14 00:38:57.275679 | 2020-03-14 00:38:57.524801 | frost_days | Processing started |            5 |      2
(2 rows)

+ set +x

WARNING: this will crash all the above requests if currently still processing

Clear those jobs? (Ctrl-C to cancel, any keys to continue)

+ docker exec postgres psql -U pavics finch -c 'delete from pywps_requests where percent_done > -1 and percent_done < 100.0;'
DELETE 2
```

**Comment by tlvu** [comment] 2020-05-28 15:49
```
$ ./scripts/clear-running-wps-jobs-in-db.sh finch
+ docker exec postgres psql -U pavics finch -c 'select * from pywps_requests where percent_done > -1 and percent_done < 100.0;'
                 uuid                 | pid | operation | version |         time_start         |          time_end          | identifier  |           message            | percent_done | status 
--------------------------------------+-----+-----------+---------+----------------------------+----------------------------+-------------+------------------------------+--------------+--------
 20849e5c-9039-11ea-9762-0242ac120007 |  12 | execute   | 1.0.0   | 2020-05-07 08:02:42.13425  | 2020-05-07 08:02:46.637466 | subset_bbox | Subsetting file 1 of 1       |            5 |      2
 40542ec8-9ee9-11ea-be65-0242ac120005 |   9 | execute   | 1.0.0   | 2020-05-26 00:38:43.206854 | 2020-05-26 00:39:15.92026  | sdii        | [##             ] | 17% Done |           21 |      2
(2 rows)

+ set +x

WARNING: this will crash all the above requests if currently still processing

Clear those jobs? (Ctrl-C to cancel, any keys to continue)

+ docker exec postgres psql -U pavics finch -c 'delete from pywps_requests where percent_done > -1 and percent_done < 100.0;'
DELETE 2
```

**Comment by tlvu** [comment] 2020-07-15 00:44
```
$ ./scripts/clear-running-wps-jobs-in-db.sh finch
+ docker exec postgres psql -U pavics finch -c 'select * from pywps_requests where percent_done > -1 and percent_done < 100.0;'
                 uuid                 | pid | operation | version |         time_start         |          time_end          | identifier |           message           | percent_done | status 
--------------------------------------+-----+-----------+---------+----------------------------+----------------------------+------------+-----------------------------+--------------+--------
 7231992c-b1c6-11ea-be93-0242ac120006 |   9 | execute   | 1.0.0   | 2020-06-19 00:47:26.572813 | 2020-06-19 00:47:26.928304 | frost_days | Computing the output netcdf |            5 |      2
 3647de3e-b253-11ea-9057-0242ac120006 |  69 | execute   | 1.0.0   | 2020-06-19 17:35:05.192167 | 2020-06-19 17:35:10.093167 | frost_days | Computing the output netcdf |            5 |      2
(2 rows)

+ set +x

WARNING: this will crash all the above requests if currently still processing

Clear those jobs? (Ctrl-C to cancel, any keys to continue)

+ docker exec postgres psql -U pavics finch -c 'delete from pywps_requests where percent_done > -1 and percent_done < 100.0;'
DELETE 2
```

**Comment by tlvu** [comment] 2020-10-29 23:30
```
$ ./scripts/clear-running-wps-jobs-in-db.sh finch
+ docker exec postgres psql -U pavics finch -c 'select * from pywps_requests where percent_done > -1 and percent_done < 100.0;'
                 uuid                 | pid | operation | version |         time_start         |          time_end          | identifier  |           message            | percent_done | status 
--------------------------------------+-----+-----------+---------+----------------------------+----------------------------+-------------+------------------------------+--------------+--------
 88b165d4-f806-11ea-9f63-0242ac120009 |   8 | execute   | 1.0.0   | 2020-09-16 10:22:33.506668 | 2020-09-16 10:22:35.636361 | subset_bbox | Subsetting file 1 of 1       |            5 |      2
 375c2036-18f7-11eb-a4d7-0242ac12000e |  13 | execute   | 1.0.0   | 2020-10-28 08:26:02.972843 | 2020-10-28 08:26:34.913726 | frost_days  | [###            ] | 24% Done |           27 |      2
(2 rows)

+ set +x

WARNING: this will crash all the above requests if currently still processing

Clear those jobs? (Ctrl-C to cancel, any keys to continue)

+ docker exec postgres psql -U pavics finch -c 'delete from pywps_requests where percent_done > -1 and percent_done < 100.0;'
DELETE 2
```
